server:
  port: 8080
token:
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000
redis:
  host: localhost
  port: 6379
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lajolie
    username: huydeve
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  devtools:
    restart:
      exclude: static/**,public/**
      enabled: true
    livereload:
      enabled: true
  main:
    web-application-type: servlet
huydev:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://lajolie-api.com


#http://localhost:8080/swagger-ui/index.html#/